### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by nickmccurdy** [paircolumbus/progress#25]
Hello, is this app still in use? I haven't been in the area for meetups but I have been hosting the app on Heroku. I got a notification that mlab is getting shut down in a couple months. If you'd like to keep it up we'll need a different database service.

**Comment by jaybobo** [comment]
@nickmccurdy Yoooo sorry I was out in Mexico completely unplugged over the summer and am just seeing this now. We can host it on my Heroku account and have one of the sponsors cover the cost. We've been on hiatus because of the pandemic.
